# This file was generated by GoReleaser. DO NOT EDIT.
cask "leo" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "b11a06ea4dbeeef1003addb6e04e8199366c7b4267cdba1c7beebb038293a94d"
      url "https://github.com/StealthFactory/leo/releases/download/v#{version}/leo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "021d770a351e4e06b4421a595825fc8234b5719f9a13e1b2b2a7879def98fb8e"
      url "https://github.com/StealthFactory/leo/releases/download/v#{version}/leo_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "leo"
  desc "Personal, extensible task-runner CLI with a JSON object store"
  homepage "https://github.com/StealthFactory/leo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leo"

  # No zap stanza required
end
