# This file was generated by GoReleaser. DO NOT EDIT.
cask "leo" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "a64751d1859c523877ba6498035b2def2b7155adeda69bbd5a80c33ce7c74df0"
      url "https://github.com/StealthFactory/leo/releases/download/v#{version}/leo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa7aebe9a29a89c0dd5ca738326a1e0d5008cd33915b77eddb8ef7ecea01eaf2"
      url "https://github.com/StealthFactory/leo/releases/download/v#{version}/leo_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "leo"
  desc "Personal, extensible task-runner CLI with a JSON object store"
  homepage "https://github.com/StealthFactory/leo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leo"

  # No zap stanza required
end
