# This file was generated by GoReleaser. DO NOT EDIT.
cask "leo" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "5a8e9acc2c057cce8441a1dcda4c1129e258481dff6c42d88d8cd6b623d04ebd"
      url "https://github.com/StealthFactory/leo/releases/download/v#{version}/leo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0664642d205533afebf9fdea755144cfc99bca842f4af43f7a1414fe999de230"
      url "https://github.com/StealthFactory/leo/releases/download/v#{version}/leo_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "leo"
  desc "Personal, extensible task-runner CLI with a JSON object store"
  homepage "https://github.com/StealthFactory/leo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leo"

  # No zap stanza required
end
